apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gitrello-github-integration-service.fullname" . }}
  labels:
    {{- include "gitrello-github-integration-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "gitrello-github-integration-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.deployment.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gitrello-github-integration-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.deployment.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gitrello-github-integration-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.deployment.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.deployment.securityContext | nindent 12 }}
          image: "fnsdev/gitrello-github-integration-service:{{ .Values.deployment.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8001
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http
              httpHeaders:
                - name: Host
                  value: {{ .Values.host | quote }}
          readinessProbe:
            httpGet:
              path: /ping
              port: http
              httpHeaders:
                - name: Host
                  value: {{ .Values.host | quote }}
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
          env:
            - name: ENVIRONMENT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: environment
            - name: DB_POOL_MIN_IDLE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: db_pool_min_idle
            - name: DB_POOL_MAX_SIZE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: db_pool_max_size
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: db_url
            - name: RUST_LOG
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: rust_log
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: secret
            - name: GITRELLO_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: gitrello_host
            - name: GITRELLO_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: gitrello_url
            - name: WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: webhook_url
            - name: GITRELLO_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: gitrello_access_token
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
