apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
stringData:
  environment: {{ .Values.secret.environment | quote }}
  db_pool_min_idle: {{ .Values.secret.db_pool_min_idle | quote }}
  db_pool_max_size: {{ .Values.secret.db_pool_max_size | quote }}
  db_url: {{ .Values.secret.db_url | quote }}
  rust_log: {{ .Values.secret.rust_log | quote }}
  secret: {{ .Values.secret.secret | quote }}
  gitrello_host: {{ .Values.secret.gitrello_host | quote }}
  gitrello_url: {{ .Values.secret.gitrello_url | quote }}
  webhook_url: {{ .Values.secret.webhook_url | quote }}
  gitrello_access_token: {{ .Values.secret.gitrello_access_token | quote }}
