apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitrello-github-integration-service.fullname" . }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "gitrello-github-integration-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "gitrello-github-integration-service.selectorLabels" . | nindent 4 }}
